HomeWork2
NataliaMartynuik/nodejs-homework-02-06 pull request #1
Opened 2023-01-08 18:14 UTC by NataliaMartynuik

Привіт! Перевірте, будь ласка.

2023-01-08 18:48 UTC, KhYulian commented on app.js
> +  }
Можна скоротити. Використовуйте ||

2023-01-08 18:48 UTC, KhYulian commented on helpers/index.js
> +}
використовуйте класи

2023-01-08 18:49 UTC, KhYulian commented on schemas/contacts.js
> +});
const updateContactSchema = Joi.object({...}).min(1) - одне обовязкове поле

2023-01-08 18:50 UTC, KhYulian commented on models/contacts.js
> +  const [upContact] = contacts.filter((contact) => contact.id === contactId);
використовуйте .find()

2023-01-08 18:50 UTC, KhYulian commented on controllers/contacts.controller.js
> +const contactsDb = require('../models/contacts');
зробіть деструктуризацію

2023-01-08 18:50 UTC, KhYulian requested changes
Потрібне доопрацювання

2023-01-08 18:50 UTC, KhYulian commented
Відповідайте на коменти помірі виправлення :)

2023-01-08 21:43 UTC, NataliaMartynuik commented on schemas/contacts.js
> +});
Done

2023-01-08 22:40 UTC, NataliaMartynuik commented on controllers/contacts.controller.js
> +const contactsDb = require('../models/contacts');
Виправлено

2023-01-09 21:08 UTC, NataliaMartynuik commented on models/contacts.js
> +  const [upContact] = contacts.filter((contact) => contact.id === contactId);
Виправлено

2023-01-09 21:09 UTC, NataliaMartynuik commented on app.js
> +  }
Виправлено

2023-01-10 06:17 UTC, KhYulian commented on helpers/index.js
> +}
https://javascript.info/custom-errors

2023-01-11 20:16 UTC, NataliaMartynuik commented on helpers/index.js
> +}
Виправлено

2023-01-11 21:05 UTC, KhYulian approved these changes
Чудова робота ❤️

2023-01-11 21:05 UTC, merged