04-auth
NataliaMartynuik/nodejs-homework-02-06 pull request #3
Opened 2023-01-27 21:38 UTC by NataliaMartynuik

Привіт! Перевірте, будь ласка!!

2023-01-28 07:52 UTC, KhYulian requested changes
Потрібні правки

2023-01-28 07:52 UTC, KhYulian commented on controllers/auth.controller.js
> +      },
Уникайте надлишкової вкладеності. data можна видалити. Стосується усього коду

2023-01-28 07:52 UTC, KhYulian commented on controllers/contacts.controller.js
> +  const { page = 1, limit = 20, favorite = true } = req.query;
favorite = [true, false]
якщо просто true, то ви по дефолту виключаєте усі контакти де favorite: false з результату - це непрввильно

2023-01-28 16:01 UTC, NataliaMartynuik commented on controllers/contacts.controller.js
> +  const { page = 1, limit = 20, favorite = true } = req.query;
Виправлено.

2023-01-28 16:01 UTC, NataliaMartynuik commented on controllers/auth.controller.js
> +      },
Виправлено.

2023-01-29 08:00 UTC, KhYulian approved these changes
Чудова робота :)

2023-01-29 08:01 UTC, merged